version: "3.9"
services:
  db:
    image: mysql:8.4
    # platform: linux/arm64/v8
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"
    networks:
      - osf-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -pmysql --silent" ]
      interval: 5s
      timeout: 3s
      retries: 20
  app-spring:
   image: soza77/spring-boot-test:v1
   build: .
   # working_dir: /spring-boot-test
   environment:
     TZ: America/Sao_Paulo
     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mysqldb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
     SPRING_DATASOURCE_USERNAME: root
     SPRING_DATASOURCE_PASSWORD: mysql
     SERVER_PORT: 80
   ports:
    - "80:80"
#   command: mvn spring-boot:run
   depends_on:
     db:
       condition: service_healthy
   volumes:
     - ./uploads:/app/uploads
   networks:
     - osf-network
networks:
  osf-network:
    driver: bridge