name: SpringBootTest - Continuos Integration with Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Login
      uses: docker/login-action@v3.5.0
      with:
       username: ${{ secrets.DOCKER_USER}}
       password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Application Jar
      working-directory: ./spring-boot-test
      run: mvn clean package 

    - name: Docker Compose Build
      working-directory: ./spring-boot-test
      run: docker compose build

    - name: Push to Docker Hub Conainer Registry
      run: | 
        docker tag ${{ secrets.DOCKER_USER}}/spring-boot-test:latest ${{ secrets.DOCKER_USER}}/spring-boot-test:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-test:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-test:latest
